spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: user
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  data:
    mongodb:
      authentication-database: admin
      username: mongouser
      password: mongopassword
      database: studybel
      port: 27017
      host: localhost

  elasticsearch:
    uris: http://localhost:9200
    username: ""
    password: ""

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080