spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  data:
    mongodb:
      authentication-database: admin
      username: mongouser
      password: mongopassword
      database: studybel
      port: 27017
      host: localhost

  elasticsearch:
    uris: http://localhost:9200
    username: ""
    password: ""

  mail:
    host: smtp.gmail.com
    port: 587
    username: krakenteam64@gmail.com
    password: qfpe ykgz yvmn mjzq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages_en_GB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      security:
        protocol: PLAINTEXT
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.add.type.headers: false
      invitation-send:
        topic: "invitation-send"
      invitation-accept:
        topic: "invitation-accept"

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification-service
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
    topics:
      invitation-send:
        name: "invitation-send"
      invitation-accept:
        topic: "invitation-accept"

server:
  port: 8080

minio:
  bucket: media
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  
jwt:
  secret-key: 34b352f5e67b82f8f3825984bbffb876f4328eedc2316c47d63135059a3da293
  expiration: 2880

logging:
  level:
    org.elasticsearch.client: DEBUG
    org.apache.http: DEBUG
    co.elastic.clients: DEBUG
