spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongouser
      password: mongopassword
      database: studybel
      port: 27017
      host: localhost

  elasticsearch:
    uris: http://localhost:9200
    username: ""
    password: ""

server:
  port: 8080

minio:
  bucket: media
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin